# Data exploration and preprocessing on the SnakeCLEF2023 dataset

## References
1. Information about snake species in Vietnam [The Reptile Database](https://reptile-database.reptarium.cz/)
2. Dataset and metadata [SnakeCLEF2023](https://www.imageclef.org/SnakeCLEF2023)

## Import Library & Path

In [1]:
import pandas as pd
from pathlib import Path

# for HTML
from bs4 import BeautifulSoup
import html
import pandas as pd

# split
from sklearn.model_selection import train_test_split

# config path
DATA_DIR = Path("../data")
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"

## 1. Data exploration via metadata

In [2]:
training_df = pd.read_csv("../data/raw/SnakeCLEF2023-TrainMetadata-iNat.csv")

print("Training set information")
print("Shape:", training_df.shape)
training_df.head()

Training set information
Shape: (154301, 7)

,observation_id,endemic,binomial_name,code,image_path,class_id,subset
0,2670823,True,Zamenis lineatus,IT,1990/Zamenis_lineatus/3001242.jpg,1779,train
1,70108926,False,Xenoxybelis argenteus,VE,1990/Xenoxybelis_argenteus/113910655.jpg,1772,train
2,70108926,False,Xenoxybelis argenteus,VE,1990/Xenoxybelis_argenteus/113910659.jpg,1772,train
3,117935,False,Aspidelaps lubricus,ZA,1990/Aspidelaps_lubricus/168477.JPG,95,train
4,125284,False,Telescopus beetzi,ZA,1990/Telescopus_beetzi/177365.JPG,1606,train

In [3]:
print(training_df.isna().sum())

duplicate_rows = training_df[training_df.duplicated(keep=False)]
print(f"Duplicate rows: {len(duplicate_rows)}")
print(duplicate_rows)

training_df = training_df.drop_duplicates(keep="first").reset_index(drop=True)
print(f"Rows after removing duplicates: {len(training_df)}")

observation_id    0
endemic           0
binomial_name     0
code              0
image_path        0
class_id          0
subset            0
dtype: int64
Duplicate rows: 10
       observation_id  endemic          binomial_name code  \
25961        38743171    False         Boiga melanota   TH
25962        38743171    False         Boiga melanota   TH
26131        38743135    False           Boiga cyanea   TH
26132        38743135    False           Boiga cyanea   TH
26783        33790188    False  Pseudoxenodon macrops   IN
32482        38743171    False         Boiga melanota   TH
32483        38743171    False         Boiga melanota   TH
32495        38743135    False           Boiga cyanea   TH
32496        38743135    False           Boiga cyanea   TH
32579        33790188    False  Pseudoxenodon macrops   IN

                                     image_path  class_id subset
25961         2017/Boiga_melanota/61623652.jpeg       192  train
25962          2017/Boiga_melanota/61623683.jpg       192  train
26131           2017/Boiga_cyanea/61623546.jpeg       182  train
26132           2017/Boiga_cyanea/61623587.jpeg       182  train
26783  2017/Pseudoxenodon_macrops/53108300.jpeg      1402  train
32482         2017/Boiga_melanota/61623652.jpeg       192  train
32483          2017/Boiga_melanota/61623683.jpg       192  train
32495           2017/Boiga_cyanea/61623546.jpeg       182  train
32496           2017/Boiga_cyanea/61623587.jpeg       182  train
32579  2017/Pseudoxenodon_macrops/53108300.jpeg      1402  train
Rows after removing duplicates: 154296

In [4]:
additional_training_df = pd.read_csv("../data/raw/SnakeCLEF2023-TrainMetadata-HM.csv")

print("Additional training set information")
print("Shape:", additional_training_df.shape)
additional_training_df.head()

Additional training set information
Shape: (13843, 7)

,observation_id,binomial_name,image_path,subset,code,endemic,class_id
0,HM 1954,Thamnophis butleri,HMP/Thamnophis_butleri/2408.jpg,train-hm,US,False,1619
1,HM 1955,Thamnophis butleri,HMP/Thamnophis_butleri/2409.jpg,train-hm,US,False,1619
2,HM 23990,Thamnophis butleri,HMP/Thamnophis_butleri/39886.jpg,train-hm,US,False,1619
3,HM 23991,Thamnophis butleri,HMP/Thamnophis_butleri/39887.jpg,train-hm,US,False,1619
4,HM 23991,Thamnophis butleri,HMP/Thamnophis_butleri/39888.jpg,train-hm,US,False,1619

In [5]:
print(additional_training_df.isna().sum())

duplicate_images = additional_training_df[additional_training_df.duplicated(subset=["image_path"], keep=False)]
print(f"Duplicate images: {len(duplicate_images)}")
print(duplicate_images)

additional_training_df = additional_training_df.drop_duplicates(subset=["image_path"], keep="first").reset_index(drop=True)
print(f"Rows after removing duplicates: {len(additional_training_df)}")

observation_id     0
binomial_name      0
image_path         0
subset             0
code              59
endemic            0
class_id           0
dtype: int64
Duplicate images: 0
Empty DataFrame
Columns: [observation_id, binomial_name, image_path, subset, code, endemic, class_id]
Index: []
Rows after removing duplicates: 13843

In [6]:
validation_df = pd.read_csv("../data/raw/SnakeCLEF2023-ValMetadata.csv")

print("Validation set information")
print("Shape:", validation_df.shape)
validation_df.head()

Validation set information
Shape: (14117, 8)

,observation_id,captive,endemic,binomial_name,code,image_path,class_id,subset
0,125279,False,False,Psammophis namibensis,ZA,1992/Psammophis_namibensis/177357.JPG,1347,val
1,2393541,False,False,Lampropeltis annulata,US,1993/Lampropeltis_annulata/2666703.jpg,861,val
2,122004,False,False,Atractus occipitoalbus,EC,1994/Atractus_occipitoalbus/174083.JPG,136,val
3,117794,False,False,Psomophis genimaculatus,PY,1995/Psomophis_genimaculatus/168329.JPG,1405,val
4,117810,False,False,Phalotris tricolor,PY,1996/Phalotris_tricolor/168351.JPG,1260,val

In [7]:
print(validation_df.isna().sum())

duplicate_images = validation_df[validation_df.duplicated(subset=["image_path"], keep=False)]
print(f"Duplicate images: {len(duplicate_images)}")
print(duplicate_images)

validation_df = validation_df.drop_duplicates(subset=["image_path"], keep="first").reset_index(drop=True)
print(f"Rows after removing duplicates: {len(validation_df)}")

observation_id    0
captive           0
endemic           0
binomial_name     0
code              0
image_path        0
class_id          0
subset            0
dtype: int64
Duplicate images: 0
Empty DataFrame
Columns: [observation_id, captive, endemic, binomial_name, code, image_path, class_id, subset]
Index: []
Rows after removing duplicates: 14117

In [8]:
testing_df = pd.read_csv("../data/raw/SnakeCLEF2023-PubTestMetadata.csv")

print("Test set information")
print("Shape:", testing_df.shape)
testing_df.head()

Test set information
Shape: (14071, 5)

   observation_id  captive  endemic code            image_path
0         5954638    False    False   US   pubtest/7437408.jpg
1         3074568    False    False   ID   pubtest/3543837.jpg
2        37207473    False    False   US  pubtest/58945588.jpg
3        37280098    False    False   TH  pubtest/59067915.jpg
4          116571    False    False   GY    pubtest/166608.JPG

In [9]:
print(testing_df.isna().sum())

duplicate_images = testing_df[testing_df.duplicated(subset=["image_path"], keep=False)]
print(f"Duplicate images: {len(duplicate_images)}")
print(duplicate_images)

testing_df = testing_df.drop_duplicates(subset=["image_path"], keep="first").reset_index(drop=True)
print(f"Rows after removing duplicates: {len(testing_df)}")

observation_id    0
captive           0
endemic           0
code              0
image_path        0
dtype: int64
Duplicate images: 0
Empty DataFrame
Columns: [observation_id, captive, endemic, code, image_path]
Index: []
Rows after removing duplicates: 14071

## 2. Extract snake species found in Vietnam from The Reptile Database. (Extract via HTML)

In [10]:
with open("../data/raw/ReptileDatabase-VNSpecies.html", "r", encoding="utf-8") as f:
    source_page = BeautifulSoup(f, "html.parser")

raw_html = "\n".join(line.get_text() for line in source_page.select(".line-content"))
soup = BeautifulSoup(html.unescape(raw_html), "html.parser")
species_names = [tag.get_text(strip=True) for tag in soup.select("li a em")]
vietnam_snakes = pd.DataFrame({"scientific_name": species_names})

print("Shape:", vietnam_snakes.shape)
vietnam_snakes.head()

Shape: (282, 1)

       scientific_name
0       Achalinus ater
1    Achalinus emilyae
2    Achalinus juliani
3     Achalinus quangi
4  Achalinus rufescens

In [11]:
vietnam_snakes.to_csv("../data/raw/ReptileDatabase-VNSpecies.csv", index=False)

## 3. Concatenate the training dataset with the additional dataset to create a large training dataset.

In [12]:
combined_training_df = pd.concat([training_df, additional_training_df], ignore_index=True)

print("Combined training set")
print("Shape:", combined_training_df.shape)
print("Species:", combined_training_df["binomial_name"].nunique())
print("Observations:", combined_training_df["observation_id"].nunique())

combined_training_df.head()

Combined training set
Shape: (168139, 7)
Species: 1784
Observations: 95588

,observation_id,endemic,binomial_name,code,image_path,class_id,subset
0,2670823,True,Zamenis lineatus,IT,1990/Zamenis_lineatus/3001242.jpg,1779,train
1,70108926,False,Xenoxybelis argenteus,VE,1990/Xenoxybelis_argenteus/113910655.jpg,1772,train
2,70108926,False,Xenoxybelis argenteus,VE,1990/Xenoxybelis_argenteus/113910659.jpg,1772,train
3,117935,False,Aspidelaps lubricus,ZA,1990/Aspidelaps_lubricus/168477.JPG,95,train
4,125284,False,Telescopus beetzi,ZA,1990/Telescopus_beetzi/177365.JPG,1606,train

## 4. Filter Vietnam species

In [13]:
# Checking class id vs binomial_name
name_count = combined_training_df["binomial_name"].nunique()
class_count = combined_training_df["class_id"].nunique()

print("Scientific names:", name_count)
print("Class IDs:", class_count)
print("Same number:", name_count == class_count)
print("Each name maps to one class ID:", combined_training_df.groupby("binomial_name")["class_id"].nunique().max() == 1)
print("Each class ID maps to one name:",combined_training_df.groupby("class_id")["binomial_name"].nunique().max() == 1)

Scientific names: 1784
Class IDs: 1784
Same number: True
Each name maps to one class ID: True
Each class ID maps to one name: True

In [14]:
vietnam_species = set(vietnam_snakes["scientific_name"])
snakeclef_species = set(combined_training_df["binomial_name"])
matched_species = vietnam_species & snakeclef_species

print("Vietnam species master:", len(vietnam_species))
print("SnakeCLEF species:", len(snakeclef_species))
print("Matched Vietnam species:", len(matched_species))

vietnam_training_df = combined_training_df[combined_training_df["binomial_name"].isin(matched_species)].copy()

print("Images:", len(vietnam_training_df))
print("Observations:", vietnam_training_df["observation_id"].nunique())
vietnam_training_df.head()

Vietnam species master: 282
SnakeCLEF species: 1784
Matched Vietnam species: 160
Images: 23896
Observations: 14027

,observation_id,endemic,binomial_name,code,image_path,class_id,subset
12,37280129,False,Amphiesma stolatum,TH,1990/Amphiesma_stolatum/59067968.jpg,66,train
14,37280100,False,Oligodon taeniatus,TH,1990/Oligodon_taeniatus/59067926.jpg,1182,train
55,37315747,False,Ophiophagus hannah,TH,1992/Ophiophagus_hannah/59128457.jpg,1190,train
138,72056263,False,Plagiopholis nuchalis,TH,1996/Plagiopholis_nuchalis/117415705.jpeg,1298,train
176,49563464,False,Ophiophagus hannah,IN,1998/Ophiophagus_hannah/78681344.jpg,1190,train

## 5. Analyze species

In [15]:
species_counts = (vietnam_training_df.groupby("binomial_name").size().sort_values(ascending=False))

print("Matched Vietnam species:", species_counts.shape[0])
print(species_counts.describe())

print("\n>= 500 images:", (species_counts >= 500).sum())
print(">= 250 images:", (species_counts >= 200).sum())
print(">= 100 images:", (species_counts >= 100).sum())
print(">= 50 images:", (species_counts >= 50).sum())
print("< 50 images:", (species_counts < 50).sum())

species_counts.head()

Matched Vietnam species: 160
count     160.000000
mean      149.350000
std       166.238224
min         3.000000
25%        31.000000
50%        93.500000
75%       207.250000
max      1122.000000
dtype: float64

>= 500 images: 7
>= 250 images: 43
>= 100 images: 74
>= 50 images: 107
< 50 images: 53

binomial_name
Indotyphlops braminus           1122
Psammodynastes pulverulentus     698
Dendrelaphis pictus              593
Ptyas mucosa                     569
Ahaetulla prasina                565
dtype: int64

## 6. Add medically important venomous snake (MIVS) & select final classes

In [16]:
mivs_df = pd.read_csv("http://ptak.felk.cvut.cz/plants/plants/SnakeCLEF2023/venomous_status_list.csv")
mask = mivs_df["MIVS"] == 1

print("Shape: ", mivs_df.shape)
print("Has venomous: ", mask.sum())
mivs_df.head()

Shape:  (1784, 2)
Has venomous:  285

   class_id  MIVS
0      1779     0
1      1772     0
2        95     0
3      1606     0
4       561     0

In [17]:
candidate_stats = species_counts.reset_index()
candidate_stats.columns = ["binomial_name", "image_count"]

class_map = vietnam_training_df[["binomial_name", "class_id"]].drop_duplicates()

candidate_stats = candidate_stats.merge(class_map, on="binomial_name",how="left")
candidate_stats = candidate_stats.merge(mivs_df, on="class_id", how="left")

candidate_stats = candidate_stats[["binomial_name", "image_count", "class_id", "MIVS"]]

print(candidate_stats["MIVS"].value_counts(dropna=False))
candidate_stats.head()

MIVS
0    138
1     22
Name: count, dtype: int64

                  binomial_name  image_count  class_id  MIVS
0         Indotyphlops braminus         1122       849     0
1  Psammodynastes pulverulentus          698      1334     0
2           Dendrelaphis pictus          593       499     0
3                  Ptyas mucosa          569      1414     0
4             Ahaetulla prasina          565        47     0

In [18]:
# select final classes
final_classes = candidate_stats[(candidate_stats["MIVS"] == 1) |(candidate_stats["image_count"] >= 50)].copy()
final_classes = final_classes.sort_values(["MIVS", "image_count"], ascending=[False, False]).reset_index(drop=True)

print("Final classes:", len(final_classes))
print("MIVS classes:", (final_classes["MIVS"] == 1).sum())
print("Non-MIVS classes:", (final_classes["MIVS"] == 0).sum())

final_classes.describe()

Final classes: 109
MIVS classes: 22
Non-MIVS classes: 87

       image_count     class_id        MIVS
count   109.000000   109.000000  109.000000
mean    209.449541   932.091743    0.201835
std     170.836097   516.970297    0.403224
min      32.000000     9.000000    0.000000
25%      92.000000   470.000000    0.000000
50%     154.000000   959.000000    0.000000
75%     280.000000  1408.000000    0.000000
max    1122.000000  1769.000000    1.000000

In [19]:
print(final_classes.isna().sum())
final_classes.head()

binomial_name    0
image_count      0
class_id         0
MIVS             0
dtype: int64

             binomial_name  image_count  class_id  MIVS
0       Ophiophagus hannah          486      1190     1
1       Bungarus fasciatus          430       259     1
2  Trimeresurus albolabris          421      1662     1
3      Rhabdophis tigrinus          376      1452     1
4    Tropidolaemus wagleri          292      1714     1

## 7. Build class mapping

In [20]:
class_mapping = (final_classes.sort_values("class_id").reset_index(drop=True).copy())
class_mapping["label_idx"] = range(len(class_mapping))
class_mapping = class_mapping[["label_idx", "class_id", "binomial_name", "MIVS", "image_count"]]

print("Number of classes:", len(class_mapping))
class_mapping.head()

Number of classes: 109

   label_idx  class_id           binomial_name  MIVS  image_count
0          0         9     Achalinus rufescens     0           91
1          1        14  Acrochordus granulatus     0          152
2          2        40         Ahaetulla fusca     0           65
3          3        47       Ahaetulla prasina     0          565
4          4        66      Amphiesma stolatum     0          368

In [21]:
print("Unique labels:", class_mapping["label_idx"].nunique())
print("Unique class IDs:", class_mapping["class_id"].nunique())
print("Unique species:", class_mapping["binomial_name"].nunique())

assert class_mapping["label_idx"].tolist() == list(range(len(class_mapping)))

Unique labels: 109
Unique class IDs: 109
Unique species: 109

## 8. Filter for validation set

In [22]:
final_class_ids = set(final_classes["class_id"])
filtered_validation_df = validation_df[validation_df["class_id"].isin(final_class_ids)].copy()

print("Validation images:", len(filtered_validation_df))
print("Validation species:", filtered_validation_df["class_id"].nunique())
print("Missing values:")
print(filtered_validation_df.isna().sum())

filtered_validation_df.head()

Validation images: 1809
Validation species: 108
Missing values:
observation_id    0
captive           0
endemic           0
binomial_name     0
code              0
image_path        0
class_id          0
subset            0
dtype: int64

,observation_id,captive,endemic,binomial_name,code,image_path,class_id,subset
135,66942196,False,False,Laticauda colubrina,TW,2006/Laticauda_colubrina/108034512.jpeg,887,val
152,12603203,False,False,Cylindrophis jodiae,TH,2006/Cylindrophis_jodiae/18220665.jpg,457,val
153,12603203,False,False,Cylindrophis jodiae,TH,2006/Cylindrophis_jodiae/28581872.jpeg,457,val
176,66035963,False,False,Ophiophagus hannah,TH,2007/Ophiophagus_hannah/106370241.jpg,1190,val
186,48635831,False,False,Boiga dendrophila,MY,2007/Boiga_dendrophila/77182456.jpg,184,val

## 9. Prepare Metadata

### Why We Do Not Use the Official Public Test Set

The official SnakeCLEF 2023 Public Test metadata does not provide ground-truth labels such as `class_id` or `binomial_name`. Therefore, it cannot be used to calculate classification metrics such as accuracy, F1-score, or Top-K accuracy.

For this project, the original training data is split by `observation_id` into training and validation sets to avoid data leakage between images from the same observation. The official SnakeCLEF validation set is then used as the final labeled test set for model evaluation.

This results in the following evaluation setup:

- **Train set:** model training
- **Validation set:** hyperparameter tuning and early stopping
- **Test set:** final evaluation using the official SnakeCLEF validation data

In [23]:
final_class_ids = set(final_classes["class_id"])
full_train_metadata = vietnam_training_df[vietnam_training_df["class_id"].isin(final_class_ids)].copy()
full_train_metadata = full_train_metadata.merge(class_mapping[["class_id", "label_idx", "MIVS"]], on="class_id", how="left")

print("Images:", len(full_train_metadata))
print("Species:", full_train_metadata["class_id"].nunique())
print("Observations:", full_train_metadata["observation_id"].nunique())
print("Has missing values:", full_train_metadata.isna().any().any())

Images: 22830
Species: 109
Observations: 13418
Has missing values: False

In [24]:
observation_class_count = (full_train_metadata.groupby("observation_id")["class_id"].nunique())
print("Observations mapped to >1 class:", (observation_class_count > 1).sum())

observation_df = (full_train_metadata[["observation_id", "class_id"]].drop_duplicates())
observation_counts = observation_df["class_id"].value_counts()
print("Minimum observations per class:", observation_counts.min())

Observations mapped to >1 class: 0
Minimum observations per class: 16

In [25]:
train_observations, val_observations = train_test_split(observation_df, test_size=0.1, random_state=42, stratify=observation_df["class_id"])
train_metadata = full_train_metadata[full_train_metadata["observation_id"].isin(train_observations["observation_id"])].copy()
val_metadata = full_train_metadata[full_train_metadata["observation_id"].isin(val_observations["observation_id"])].copy()

print("Train images:", len(train_metadata))
print("Train observations:", train_metadata["observation_id"].nunique())
print("Train species:", train_metadata["class_id"].nunique())

print("\nValidation images:", len(val_metadata))
print("Validation observations:", val_metadata["observation_id"].nunique())
print("Validation species:", val_metadata["class_id"].nunique())

overlap = set(train_metadata["observation_id"]) & set(val_metadata["observation_id"])
print("Train/Val observation overlap:", len(overlap))

Train images: 20497
Train observations: 12076
Train species: 109

Validation images: 2333
Validation observations: 1342
Validation species: 109
Train/Val observation overlap: 0

In [26]:
test_metadata = filtered_validation_df.copy()
test_metadata = test_metadata.merge(class_mapping[["class_id", "label_idx", "MIVS"]], on="class_id", how="left")
test_metadata = test_metadata[
    [
        "observation_id",
        "binomial_name",
        "class_id",
        "label_idx",
        "image_path",
        "MIVS"
    ]
]

print("Test images:", len(test_metadata))
print("Test species:", test_metadata["class_id"].nunique())
print("Missing values:", test_metadata.isna().any().any())

test_metadata.head()

Test images: 1809
Test species: 108
Missing values: False

,observation_id,binomial_name,class_id,label_idx,image_path,MIVS
0,66942196,Laticauda colubrina,887,49,2006/Laticauda_colubrina/108034512.jpeg,0
1,12603203,Cylindrophis jodiae,457,25,2006/Cylindrophis_jodiae/18220665.jpg,0
2,12603203,Cylindrophis jodiae,457,25,2006/Cylindrophis_jodiae/28581872.jpeg,0
3,66035963,Ophiophagus hannah,1190,66,2007/Ophiophagus_hannah/106370241.jpg,1
4,48635831,Boiga dendrophila,184,6,2007/Boiga_dendrophila/77182456.jpg,0

## 10. Final checks & Save

In [27]:
final_class_ids = set(class_mapping["class_id"])

print("Train:", len(train_metadata), "images |", train_metadata["class_id"].nunique(), "classes")
print("Val:", len(val_metadata), "images |", val_metadata["class_id"].nunique(), "classes")
print("Test:", len(test_metadata), "images |", test_metadata["class_id"].nunique(), "classes")
print("Final classes:", len(class_mapping))

print("\nMissing values:")
print("Train:", train_metadata.isna().any().any())
print("Val:", val_metadata.isna().any().any())
print("Test:", test_metadata.isna().any().any())

print("\nInvalid class IDs:")
print("Train:", len(set(train_metadata["class_id"]) - final_class_ids))
print("Val:", len(set(val_metadata["class_id"]) - final_class_ids))
print("Test:", len(set(test_metadata["class_id"]) - final_class_ids))

train_val_overlap = set(train_metadata["observation_id"]) & set(val_metadata["observation_id"])
print("\nTrain/Val observation overlap:", len(train_val_overlap))

print("\nDuplicate image_path within each split:")

print("Train:", train_metadata["image_path"].duplicated().sum())
print("Val:", val_metadata["image_path"].duplicated().sum())
print("Test:", test_metadata["image_path"].duplicated().sum())

Train: 20497 images | 109 classes
Val: 2333 images | 109 classes
Test: 1809 images | 108 classes
Final classes: 109

Missing values:
Train: False
Val: False
Test: False

Invalid class IDs:
Train: 0
Val: 0
Test: 0

Train/Val observation overlap: 0

Duplicate image_path within each split:
Train: 0
Val: 0
Test: 0

In [28]:
processed_dir = Path("../data/processed")
processed_dir.mkdir(parents=True, exist_ok=True)

train_metadata.to_csv(processed_dir / "train.csv", index=False)
val_metadata.to_csv(processed_dir / "val.csv", index=False)
test_metadata.to_csv(processed_dir / "test.csv", index=False)
class_mapping.to_csv(processed_dir / "classes.csv", index=False)
final_classes.to_csv(processed_dir / "species_stats.csv", index=False)

print("Processed metadata saved.")

Processed metadata saved.